### ISSUE TITLE
Error 504

### ISSUE THREAD

**Issue by yeying-xingchen** [funnycups/kangle#1]
Use php -v
 error while loading shared libraries: libmysqlclient.so.16: cannot open shared object file: No such file or directory

**Comment by funnycups** [comment]
What version of kangle have you installed, and what version of Ubuntu are you using?

**Comment by funnycups** [comment]
Cannot reproduce on Ubuntu 24.04. However, I've posted 2 commits attempting to fix this problem. Please try again.

**Comment by yeying-xingchen** [comment]
Debian 12.5

**Comment by yeying-xingchen** [comment]
I noticed that during installation, a series of packages starting with PHP failed to install, indicating that the package could not be found.
我注意到在安装时，有一系列以php开头的包安装失败，提示找不到包。

**Comment by funnycups** [comment]
脚本最初并不是为debian设计的，因为ppa:ondrej/php包是ubuntu下的，所以只支持ubuntu。我正在给这个脚本添加debian支持，稍后回复你。

**Comment by funnycups** [comment]
已经添加Debian支持，并在Debian12.0上成功安装，请测试。

**Comment by yeying-xingchen** [comment]
测试完毕，Debian12.5可正常使用，谢谢！
